export const styles: Record<string, React.CSSProperties> = {
  container: {
    marginTop: 24,
    border: "1px solid #3a4050",
    borderRadius: 8,
    padding: 16,
    background: "#252525",
    overflowX: "auto",
  },
  headerBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    gap: 12,
    flexWrap: "wrap",
  },
  actionsBar: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
  },
  title: {
    fontSize: 14,
    fontWeight: 600,
    margin: 0,
    color: "#b0b8d4",
  },
  searchInput: {
    height: 30,
    padding: "0 8px",
    borderRadius: 6,
    border: "1px solid #3a4050",
    background: "#2a2a2a",
    color: "#e0e0e0",
    fontSize: 12,
  },
  button: {
    padding: "8px 12px",
    fontSize: 12,
    fontWeight: 600,
    background: "#0066cc",
    color: "#ffffff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    transition: "background 0.2s ease",
  },
  tableWrapper: {
    overflowX: "auto",
    width: "100%",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 12,
    minWidth: "600px",
  },
  row: {
    borderBottom: "1px solid #3a4050",
  },
  cell: {
    padding: "8px 12px",
    border: "1px solid #3a4050",
    textAlign: "center",
    color: "#e0e0e0",
  },
  filterInput: {
    height: 28,
    padding: "0 6px",
    width: "100%",
    borderRadius: 6,
    border: "1px solid #3a4050",
    background: "#2a2a2a",
    color: "#e0e0e0",
    fontSize: 12,
  },
  actionGroup: {
    display: "flex",
    gap: 8,
    justifyContent: "center",
  },
  actionButton: {
    padding: "4px 8px",
    fontSize: 12,
    borderRadius: 6,
    border: "1px solid #3a4050",
    background: "#2a2a2a",
    color: "#e0e0e0",
    cursor: "pointer",
  },
};
